title: Umar Syam
logo: /assets/img/headshot_circle.png
description: Computer Science Fresh Graduate | Proficient in Python, SQL & Data Visualization | Passionate About Turning Data into Insights
show_downloads: true
theme: jekyll-theme-minimal
